project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Crime Analysis of LA"
  author:
    - Debbie Dai (fd2585)
    - Yueran Wang (yw4441)
  repo-url: https://github.com/DebbieDai07/EDAV_final_LACrime.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


